# Generated by Django 5.1.7 on 2025-05-15 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noctra_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprofile',
            name='managed_by',
        ),
        migrations.AddField(
            model_name='club',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubprofile',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_profile', to='noctra_app.club'),
        ),
        migrations.DeleteModel(
            name='ClubAdmin',
        ),
    ]
