# Generated by Django 5.1.7 on 2025-04-10 00:12

import noctra_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noctra_app', '0002_tag_remove_comment_user_remove_post_club_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='is_video',
        ),
        migrations.AddField(
            model_name='post',
            name='is_ad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='file_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to=noctra_app.models.post_media_upload_path),
        ),
    ]
