# Generated by Django 5.1.7 on 2025-05-15 05:59

import noctra_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noctra_app', '0002_remove_clubprofile_managed_by_club_admins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='clubprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='club',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pictures/default_profile.jpg', null=True, upload_to=noctra_app.models.upload_club_profile_pic),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='cover_pic',
            field=models.ImageField(blank=True, default='images/cover_pictures/default_cover.jpg', null=True, upload_to=noctra_app.models.upload_club_cover_pic),
        ),
    ]
