# Generated by Django 5.1.7 on 2025-05-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noctra_app', '0003_remove_club_image_url_remove_clubprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='main_location',
            new_name='company_main_location',
        ),
    ]
