# Generated by Django 5.1.7 on 2025-04-12 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noctra_app', '0003_alter_post_mentions_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_mentioned', to='noctra_app.post'),
        ),
    ]
